
- name: Extract backend files into /etc/node_project
  unarchive:
    src: /root/project/artifact.tar.gz 
    dest: /home/ubuntu
  register: untar
    
- name: "start server"
  become: true
  shell: |
        npm install
        pm2 stop default
        pm2 start npm -- start